<?php require_once __DIR__ . '/../includes/config.php'; require_once __DIR__ . '/../includes/db.php'; require_once __DIR__ . '/../includes/functions.php'; require_once __DIR__ . '/../includes/header.php'; require_role(['admin']);
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();if(isset($_POST['approve_reg'])){db()->prepare('UPDATE registrations SET status="approved" WHERE id=?')->execute([(int)$_POST['approve_reg']]);}
if(isset($_POST['approve_result'])){db()->prepare('UPDATE results SET approved=1 WHERE id=?')->execute([(int)$_POST['approve_result']]);}}
$stats=['students'=>db()->query("SELECT COUNT(*) c FROM users WHERE role='student'")->fetch()['c'],'lecturers'=>db()->query("SELECT COUNT(*) c FROM users WHERE role='lecturer'")->fetch()['c'],'payments'=>db()->query('SELECT COUNT(*) c FROM payments')->fetch()['c']];
$pendingRegs=db()->query("SELECT r.id,u.full_name,c.code FROM registrations r JOIN users u ON u.id=r.student_id JOIN courses c ON c.id=r.course_id WHERE r.status='pending' LIMIT 10")->fetchAll();
$pendingResults=db()->query('SELECT id,student_id,course_id,score FROM results WHERE approved=0 LIMIT 10')->fetchAll(); ?>
<div class="container"><div class="card"><h2>Admin Analytics</h2><div class="grid"><?php foreach($stats as $k=>$v): ?><div class="card"><h4><?= esc(ucfirst($k)) ?></h4><p><?= esc((string)$v) ?></p></div><?php endforeach; ?></div><canvas id="analyticsChart"></canvas></div>
<div class="card"><h3>Approve Course Registrations</h3><?php foreach($pendingRegs as $p): ?><form method="POST"><input type="hidden" name="csrf_token" value="<?= esc(csrf_token()) ?>"><span><?= esc($p['full_name'].' - '.$p['code']) ?></span><button name="approve_reg" value="<?= $p['id'] ?>">Approve</button></form><?php endforeach; ?></div>
<div class="card"><h3>Result Approval</h3><?php foreach($pendingResults as $r): ?><form method="POST"><input type="hidden" name="csrf_token" value="<?= esc(csrf_token()) ?>"><span>Student #<?= esc((string)$r['student_id']) ?> Course #<?= esc((string)$r['course_id']) ?> Score <?= esc((string)$r['score']) ?></span><button name="approve_result" value="<?= $r['id'] ?>">Approve</button></form><?php endforeach; ?></div>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>new Chart(document.getElementById('analyticsChart'),{type:'bar',data:{labels:['Students','Lecturers','Payments'],datasets:[{data:[<?= $stats['students'] ?>,<?= $stats['lecturers'] ?>,<?= $stats['payments'] ?>],backgroundColor:['#0b4ea2','#5aa5ff','#8bc34a']}]}})</script>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
